### PR TITLE
update sqlite3 version

### PR DESCRIPTION
**Pull request by YazaiHu**
sqlite 3.1.13 it don't got the source code

### CODE REVIEW

**Comment by YazaiHu** [comment]
sqlite 3.1.13 it don't got the source code

**Comment by YazaiHu** [comment]
https://cdn.npm.taobao.org/dist/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz，It can't find

**Comment by sunsiansong** [comment]
同样的问题，3.1.13装不上，换成最新的4.0.3就好了。
node -v
v10.11.0
npm -v
6.4.1
os:macOS Mojave 10.14

**Comment by modood** [comment]
LGTM, thanks @YazaiHu

**Pull request merged**
